package com.sqsong.cryptlib

object EncryptKeys {
    val KEY_SHADER_FRAG_LUT = 0
    val KEY_SHADER_FRAG_ADJUST_IMAGE = 1
    val KEY_SHADER_FRAG_BASE = 2
    val KEY_SHADER_FRAG_BRIGHTNESS = 3
    val KEY_SHADER_FRAG_CLARITY = 4
    val KEY_SHADER_FRAG_COLOR_TEMPERATURE = 5
    val KEY_SHADER_FRAG_CONTRAST = 6
    val KEY_SHADER_FRAG_EXPOSURE = 7
    val KEY_SHADER_FRAG_GAUSSIAN_BLUR = 8
    val KEY_SHADER_FRAG_HIGHLIGHT = 9
    val KEY_SHADER_FRAG_HIGHLIGHT_SHADOW = 10
    val KEY_SHADER_FRAG_LUT_ABIGAIL = 11
    val KEY_SHADER_FRAG_LUT_ADDISON = 12
    val KEY_SHADER_FRAG_LUT_AMELIA = 13
    val KEY_SHADER_FRAG_LUT_AVA = 14
    val KEY_SHADER_FRAG_LUT_AVERY = 15
    val KEY_SHADER_FRAG_LUT_CHARLOTTE = 16
    val KEY_SHADER_FRAG_LUT_ELA = 17
    val KEY_SHADER_FRAG_LUT_ELIZABETH = 18
    val KEY_SHADER_FRAG_LUT_EMILY = 19
    val KEY_SHADER_FRAG_LUT_EMMA = 20
    val KEY_SHADER_FRAG_LUT_EVELYN = 21
    val KEY_SHADER_FRAG_LUT_HARPER = 22
    val KEY_SHADER_FRAG_LUT_ISSABELLA = 23
    val KEY_SHADER_FRAG_LUT_MADISON = 24
    val KEY_SHADER_FRAG_LUT_MIA = 25
    val KEY_SHADER_FRAG_LUT_OLIVIA = 26
    val KEY_SHADER_FRAG_LUT_SOPHIA = 27
    val KEY_SHADER_FRAG_SATURATION = 28
    val KEY_SHADER_FRAG_SHADOW = 29
    val KEY_SHADER_FRAG_SHARPEN = 30
    val KEY_SHADER_FRAG_TEMPERATURE_HUE = 31
    val KEY_SHADER_FRAG_TEST = 32
    val KEY_SHADER_FRAG_TONE = 33
    val KEY_SHADER_FRAG_VIGNETTE = 34
    val KEY_SHADER_VERT_BASE = 35
    val KEY_SHADER_VERT_NO_FILTER = 36
}